### PR TITLE
#fixed #326

### LINKED ISSUE #326: App crash if you goto user's wallet too fast

### PR DESCRIPTION
**Pull request by ue**

### CODE REVIEW

File: src/components/wallet/container/walletContainer.js [hunk 1]
```diff
@@ -29,76 +23,30 @@ class WalletContainer extends Component {
...
 
     return (
       <WalletView
-        currentAccountUsername={currentAccount.username}
-        selectedUsername={user.username}
-        {...this.props}
+        currentAccountUsername={currentAccountUsername}
+        selectedUsername={selectedUser && selectedUser.name}
         walletData={walletData}
+        intl={intl}
```
Comment (mistikk) [inline src/components/wallet/container/walletContainer.js]: we can user injectIntl on walletview, we not need to move this prop

File: src/screens/profile/screen/profileScreen.js [hunk 2]
```diff
@@ -190,7 +194,13 @@ class ProfileScreen extends PureComponent {
                 id: 'profile.wallet',
               })}
             >
-              <Wallet user={user} intl={intl} />
+              {selectedUser ? (
+                <Wallet selectedUser={selectedUser} intl={intl} />
+              ) : (
+                <Fragment>
+                  <WalletDetailsPlaceHolder />
+                </Fragment>
```
Comment (mistikk) [inline src/screens/profile/screen/profileScreen.js]: fragment is not require in here
