### PR TITLE
[definitely need test!] fixed #409 #410 #411

### LINKED ISSUE #409: Post preview does not render <center> tag correctly
#### Expected behavior
I expect the text between the center tag to be at the center of the published/preview page.

#### Actual behavior
The texts incorporated with center tag `<center> Text </center>` is left align. 

#### How to reproduce
- Launch app
- Open the editor's page
- Write text between the <center> tag 
- check the preview or the published page of the post with center tag

* Browser/App version: eSteem Mobile V2
* Operating system: Android 8

#### Caused
The editor/preview does not support HTML tags.

### PR DESCRIPTION
**Pull request by ue**

### CODE REVIEW

File: src/components/postElements/body/view/postBodyView.js [hunk 1]
```diff
@@ -13,6 +14,14 @@ import { default as ROUTES } from '../../../../constants/routeNames';
 // Components
 
 const WIDTH = Dimensions.get('window').width;
+const CUSTOM_RENDERERS = {
```
Comment (mistikk) [inline src/components/postElements/body/view/postBodyView.js]: can you remove this
