### PR TITLE
Fixed login issue, changed pin code structure. Also fixed #331 fixed #332

### LINKED ISSUE #331: When you add account, it replaces the previous logged in account

### LINKED ISSUE #332: Users can't sign in with posting and active key

### PR DESCRIPTION
**Pull request by mistikk**
fixed #331 
fixed #332

### CODE REVIEW

File: src/providers/steem/auth.js [hunk 1]
```diff
@@ -33,23 +32,23 @@ export const login = async (username, password) => {
...
     );
   }
-
   // Public keys of user
   const publicKeys = {
-    active: account.active.key_auths.map(x => x[0]),
-    memo: account.memo_key,
-    owner: account.owner.key_auths.map(x => x[0]),
-    posting: account.posting.key_auths.map(x => x[0]),
+    activeKey: account.active.key_auths.map(x => x[0])[0],
```
Comment (feruzm) [inline src/providers/steem/auth.js]: hmm have you tested this with different accounts? Because some accounts have multiple key_auths and index [0][0] might catch different publickey. for example: https://steemd.com/@hellosteem

File: src/screens/application/container/applicationContainer.js [hunk 2]
```diff
@@ -255,6 +291,7 @@ const mapStateToProps = state => ({
   currentAccountUsername: state.account.currentAccount.name,
   otherAccounts: state.account.otherAccounts,
   pinCode: state.account.pin,
+  currentAccountAuthType: state.account.currentAccount.local,
```
Comment (ue) [inline src/screens/application/container/applicationContainer.js]: lets get just crrentAccount from state because its calling twice time for name and also local thing.

File: src/screens/application/container/applicationContainer.js [hunk 3]
```diff
@@ -102,28 +106,52 @@ class ApplicationContainer extends Component {
...
         });
       }
     });
 
-    if (realmData) {
-      await getUser(currentUsername)
+    if (realmData.length > 0) {
+      const realmObject = realmData.filter(data => data.username === currentUsername);
+
+      if (realmObject.length <= 0) {
```
Comment (ue) [inline src/screens/application/container/applicationContainer.js]: just change it `realmObject.lenght === 0`

File: src/screens/application/container/applicationContainer.js [hunk 4]
```diff
@@ -102,28 +106,52 @@ class ApplicationContainer extends Component {
...
+                && !accountData.memoKey
+              ) {
+                realmData.splice(index, 1);
+                if (realmData.length <= 0) {
+                  dispatch(login(false));
+                  dispatch(logoutDone());
+                  removePinCode();
+                  setAuthStatus({ isLoggedIn: false });
+                  setExistUser(false);
+                  if (accountData.authType === 'steemConnect') {
```
Comment (ue) [inline src/screens/application/container/applicationContainer.js]: use constant from `constants/authType`

File: src/screens/application/container/applicationContainer.js [hunk 5]
```diff
@@ -102,28 +106,52 @@ class ApplicationContainer extends Component {
...
+            userData.forEach((accountData, index) => {
+              if (
+                !accountData.accessToken
+                && !accountData.masterKey
+                && !accountData.postingKey
+                && !accountData.activeKey
+                && !accountData.memoKey
+              ) {
+                realmData.splice(index, 1);
+                if (realmData.length <= 0) {
```
Comment (ue) [inline src/screens/application/container/applicationContainer.js]: same as follow

File: src/providers/steem/auth.js [hunk 6]
```diff
@@ -128,133 +138,70 @@ export const loginWithSC2 = async (code) => {
...
-      return response;
-    });
+  try {
+    await setPinCode(data.pinCode);
+    const users = await getUserData();
+    if (users.length > 0) {
+      users.forEach(async (userData) => {
+        if (userData.authType === 'masterKey') {
+          data.password = decryptKey(userData.masterKey, data.oldPinCode);
+        } else if (userData.authType === 'steemConnect') {
```
Comment (ue) [inline src/providers/steem/auth.js]: can use constant

File: src/providers/steem/auth.js [hunk 7]
```diff
@@ -128,133 +138,70 @@ export const loginWithSC2 = async (code) => {
...
-
-      await setAuthStatus(authData);
-      return response;
-    });
+  try {
+    await setPinCode(data.pinCode);
+    const users = await getUserData();
+    if (users.length > 0) {
+      users.forEach(async (userData) => {
+        if (userData.authType === 'masterKey') {
```
Comment (ue) [inline src/providers/steem/auth.js]: can use constant

File: src/providers/steem/auth.js [hunk 8]
```diff
@@ -128,133 +138,70 @@ export const loginWithSC2 = async (code) => {
...
-        currentUsername: userData.username,
-      };
-
-      await setAuthStatus(authData);
-      return response;
-    });
+  try {
+    await setPinCode(data.pinCode);
+    const users = await getUserData();
+    if (users.length > 0) {
```
Comment (ue) [inline src/providers/steem/auth.js]: users can be return as nulll in that case this line goes crush

File: src/providers/steem/auth.js [hunk 9]
```diff
@@ -116,9 +120,15 @@ export const loginWithSC2 = async (code) => {
     }
 
     setUserData(userData)
-      .then(() => {
+      .then(async () => {
         account.account.username = account.account.name;
```
Comment (ue) [inline src/providers/steem/auth.js]: lets changed first name acccount.accont seems weird

File: src/providers/steem/dsteem.js [hunk 10]
```diff
@@ -735,9 +731,8 @@ export const postContent = async (
 // Re-blog
 export const reblog = async (account, pinCode, author, permlink) => {
   const pin = getDigitPinCode(pinCode);
-
-  if (account.local.authType === AUTH_TYPE.MASTER_KEY) {
-    const key = decryptKey(account.local.postingKey, pin);
+  const key = getAnyPrivateKey(account.local, pin);
+  if (account.local.authType !== AUTH_TYPE.STEEM_CONNECT && key) {
```
Comment (ue) [inline src/providers/steem/dsteem.js]: what if key doesn't exist this should be return something
```
if(!key){
return null;
}
```
or something like that. instead both check also it can return

Comment (ue) [reply src/providers/steem/dsteem.js]: @mistikk
